# Action name
name: build

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    build:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}

            - name: build_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/release.sh
            - uses: actions/upload-artifact@v4
              with:
                name: MCUViewer_installer
                path: /__w/MCUViewer/MCUViewer/build/packages
    build_macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            token: ${{ secrets.PAT }}
          
        - name: Install Rosetta (if necessary)
          shell: bash
          run: |
            softwareupdate --install-rosetta --agree-to-license

        - name: Install Dependencies
          shell: bash
          run: |
            # Install glfw3 via Homebrew
            brew install glfw
            brew install gdb
            brew install spdlog

        - name: Build Step
          shell: bash
          run: |
            git config --global --add safe.directory /__w/MCUViewer/
            arch -x86_64 ./launch/release_macos.sh

        - uses: actions/upload-artifact@v4
          with:
            name: MCUViewer_macos
            path: ./build/packages/
    test:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
                
            - name: test_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/run_tests.sh
