# Action name
name: build

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    build:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}

            - name: build_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/release.sh
            - uses: actions/upload-artifact@v4
              with:
                name: MCUViewer_installer
                path: /__w/MCUViewer/MCUViewer/build/packages
    build_macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            token: ${{ secrets.PAT }}
          
        - name: Set up Homebrew (x86_64)
          run: |
            # Install Homebrew under x86_64 if needed
            if [[ ! -d "/usr/local/Homebrew" ]]; then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
            
        - name: Add x86_64 Homebrew to PATH
          run: |
            # Add /usr/local/bin to the front of the PATH to ensure x86_64 Homebrew is used
            echo "/usr/local/bin:$PATH" >> $GITHUB_ENV   
          
        - name: Install glfw and spdlog for x86_64
          run: |
            # Install libraries under x86_64 using Homebrew
            arch -x86_64 brew install glfw spdlog

        - name: Build Step
          shell: bash
          run: |
            git config --global --add safe.directory /__w/MCUViewer/
            arch -x86_64 ./launch/release_macos.sh

        - uses: actions/upload-artifact@v4
          with:
            name: MCUViewer_macos
            path: ./build/packages/
    test:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
                
            - name: test_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/run_tests.sh
