name: build_macos
on:
    push

jobs:
    build_macos:
      runs-on: macos-13
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            token: ${{ secrets.PAT }}
        
        - name: Install Rosetta 2 (if needed)
          run: |
            softwareupdate --install-rosetta --agree-to-license || echo "Rosetta is already installed"

        - name: Install Homebrew for x86_64
          run: |
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.bash_profile
            echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.zshrc
            eval "$(/usr/local/bin/brew shellenv)"

        - name: Add x86_64 Homebrew to PATH
          run: |
            eval "$(/usr/local/bin/brew shellenv)"
            which brew
            brew config  # Verify Homebrew configuration

        - name: Install glfw and spdlog for x86_64
          run: |
            arch -x86_64 /usr/local/bin/brew install glfw spdlog libusb

        - name: Build Step
          shell: bash
          run: |
            git config --global --add safe.directory /__w/MCUViewer/
            arch -x86_64 ./launch/release_macos.sh

        - uses: actions/upload-artifact@v4
          with:
            name: MCUViewer_macos
            path: ./build/packages/