# Action name
name: build

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    build:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}

            - name: build_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/release.sh
            - uses: actions/upload-artifact@v4
              with:
                name: MCUViewer_installer
                path: /__w/MCUViewer/MCUViewer/build/packages
    build_macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            token: ${{ secrets.PAT }}
        
        - name: Install Rosetta 2 (if needed)
          run: |
            softwareupdate --install-rosetta --agree-to-license || echo "Rosetta is already installed"

        - name: Install Homebrew for x86_64
          run: |
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.bash_profile
            echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.zshrc
            eval "$(/usr/local/bin/brew shellenv)"

        - name: Add x86_64 Homebrew to PATH
          run: |
            eval "$(/usr/local/bin/brew shellenv)"
            which brew
            brew config  # Verify Homebrew configuration

        - name: Install glfw and spdlog for x86_64
          run: |
            arch -x86_64 /usr/local/bin/brew install glfw spdlog

        - name: Build Step
          shell: bash
          run: |
            git config --global --add safe.directory /__w/MCUViewer/
            arch -x86_64 ./launch/release_macos.sh

        - uses: actions/upload-artifact@v4
          with:
            name: MCUViewer_macos
            path: ./build/packages/

    test:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
                
            - name: test_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/run_tests.sh
