name: run_tests
on:
    push

jobs:
    test:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/mingw-w64-x86-64:2
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
                
            - name: test_step
              shell: bash
              run: git config --global --add safe.directory /__w/MCUViewer/ && ./launch/run_tests.sh
